# Generated by Django 4.2.7 on 2026-01-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='photo',
            new_name='photos_phot_pexels__a46ae3_idx',
            old_name='photos_phot_pexels__idx',
        ),
        migrations.RenameIndex(
            model_name='photo',
            new_name='photos_phot_photogr_9324a9_idx',
            old_name='photos_phot_photogr_idx',
        ),
        migrations.RenameIndex(
            model_name='photo',
            new_name='photos_phot_photogr_9f9a21_idx',
            old_name='photos_phot_photogr_0_idx',
        ),
        migrations.RenameIndex(
            model_name='photo',
            new_name='photos_phot_created_84134a_idx',
            old_name='photos_phot_created_idx',
        ),
        migrations.RenameIndex(
            model_name='photofavorite',
            new_name='photos_phot_user_id_eef796_idx',
            old_name='photos_phot_user_id_idx',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
